#!/bin/bash
# <%=  __FILE__.gsub(/.*?puppet\//,@fqdn + ':') %>

# WARNING! THIS IS ALWAYS RAN VIA /bin/sh, and CANT fail else session wont start
# for emacs
# ALWAYS wrap sourcing (. /something) in if checking whether it exists else it fails
export QT_STYLE_OVERRIDE=gtk

if [ -e ~/.screenlayout/default.sh ] ; then
    ~/.screenlayout/default.sh
fi


if [ -e ~/.cache/gpg-agent-info ] ; then
    . ~/.cache/gpg-agent-info
fi
if kill -0 $SSH_AGENT_PID ; then
    echo 'agent exist, using existing one'
else
    echo 'starting new agent'
    /usr/bin/gpg-agent --sh --daemon --enable-ssh-support --write-env-file ~/.cache/gpg-agent-info
    if [ -e ~/.cache/gpg-agent-info ] ; then
        . ~/.cache/gpg-agent-info
    fi
fi
tmux new-session -d -s main
# export GPG_AGENT_INFO
# export SSH_AUTH_SOCK
# export SSH_AGENT_PID

echo $STARTUP >~/tmp/.xsesssion_basestartup

# qt5 doesnt do that by default and doesnt copy settings from qt4 ;/


if [ -e /usr/bin/nvidia-settings ] && [ /home/xani/.nvidia-settings-rc ] ; then
    echo $(sleep 30 ; /usr/bin/nvidia-settings -l) &
fi

if [ -e /home/xani/.screenlayout/default.sh ] ; then
    /home/xani/.screenlayout/default.sh
    bash -c 'sleep 240 ;  /home/xani/.screenlayout/default.sh' &
fi

touch /home/xani/env.xsession && chmod go-rwx /home/xani/env.xsession &&  export > /home/xani/env.xsession

if [ -e ~/mouse.sh ] ; then
    ~/mouse.sh
fi

if [ -e ~/.xsessionrc-local ] ; then
    ~/.xsessionrc-local
fi

# grep cap /usr/share/X11/xkb/rules/xorg.lst
# "setxkbmap -option" to clear
# capslock as ctrl
# setxkbmap -option ctrl:nocaps
# capslock as super

# so for some reason that is required to rebind capslock in xmodmap
# and if it is not present it just dies not parsing rest of file
# i'm not bothering to find workaround in xmodmap because that piece of shit
# doesn't even accept comments in xmodmap file...
setxkbmap -option caps:super

xmodmap ~/.xmodmap
<% if @type =~ /otebook/ %>
# man synaptics
# fix for synaptic mouse clicking
synclient TapButton1=1
synclient TapButton2=3 # righ click
synclient TapButton3=2 # middle click

synclient VertEdgeScroll=1
synclient VertTwoFingerScroll=0
<% end %>
export PATH=$PATH:$HOME/go/bin:/usr/games:$HOME/bin:$HOME/go/bin:$HOME/.local/bin:/home/xani/.cargo/bin
export VST_PATH=/home/xani/sync/sync/music_producing/vst/dll:/home/xani/sync/sync/music_producing/vst/linvst:/usr/lib/vst:/usr/lib/lxvst
true
echo UPDATESTARTUPTTY | gpg-connect-agent &
tmux new-window -P /home/xani/go/bin/purrbot
