#!/bin/bash
# <%= @puppet_header %>
# <%=  __FILE__.gsub(/.*?puppet\//,@fqdn + ':') %>

if [ "z$GPG_AGENT_INFO" = "z" ] ; then
    /usr/bin/gpg-agent --sh --daemon --enable-ssh-support --write-env-file /home/xani/.cache/gpg-agent-info
    source  /home/xani/.cache/gpg-agent-info
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
    export SSH_AGENT_PID
fi
echo $STARTUP >~/tmp/.xsesssion_basestartup

if [ -e /usr/bin/nvidia-settings ] && [ /home/xani/.nvidia-settings-rc ] ; then
    echo $(sleep 30 ; /usr/bin/nvidia-settings -l) &
fi

if [ -e /home/xani/.screenlayout/default.sh ] ; then
    bash -c 'sleep 20 ;  /home/xani/.screenlayout/default.sh' &
    bash -c 'sleep 240 ;  /home/xani/.screenlayout/default.sh' &
fi

if killall arbtt-capture >/dev/null 2>&1 ; then
    sleep  1
    killall -9 arbtt-capture >/dev/null 2>&1
fi
arbtt-capture --sample-rate 10 &
touch /home/xani/env.xsession && chmod go-rwx /home/xani/env.xsession &&  export > /home/xani/env.xsession

if [ -e ~/mouse.sh ] ; then
    ~/mouse.sh
fi

# grep cap /usr/share/X11/xkb/rules/xorg.lst
# "setxkbmap -option" to clear
# capslock as ctrl
# setxkbmap -option ctrl:nocaps
# capslock as super
if [ -e ~/.screenlayout/default.sh ]; then
    ~/.screenlayout/default.sh
fi
setxkbmap -option caps:super
xmodmap ~/.xmodmap
true
