# <%= @puppet_header %>
# <%=  __FILE__.gsub(/.*?repos/,@fqdn + ':') %>
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="xani"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git colorized-man catimg)

source $ZSH/oh-my-zsh.sh
source ~/.bash_functions
# User configuration

#export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export PATH="/usr/lib/go-1.18/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
export PATH=$PATH:$HOME/go/bin:/usr/games:$HOME/bin:$HOME/go/bin:$HOME/.local/bin:/home/xani/.cargo/bin
export EDITOR='/usr/local/bin/e'
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi
<%- if @goprivate -%>
export GOPRIVATE="<%= @goprivate %>"
<%- end -%>
<%= scope.function_template(['common/sh-alias-portable']) %>

<%= scope.function_template(['home/config/sh-alias-desktop']) %>
source  /usr/lib/git-core/git-sh-prompt

# tune history

HISTSIZE=1200
SAVEHIST=50000
HISTFILE=$HOME/.zhistory
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
unsetopt HIST_IGNORE_SPACE
unsetopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
# testing
setopt AUTO_PUSHD
#setopt CDABLE_VARS
#setopt ALWAYS_TO_END # completion
setopt HIST_REDUCE_BLANKS
setopt HIST_FCNTL_LOCK
# setopt CORRECT
export CORRECT_IGNORE="rm shutdown poweroff reboot halt"

# sensible cdpath
cdpath=( ~/src ~/src/my ~/src/os )

# leave backgrounded processes untouched
setopt nohup
setopt nocheckjobs

# stop randomly CDing to system user homes
unsetopt cdablevars
# stop randomly CDing on any fucking typo
unsetopt auto_cd


# stop fucking up scp
unsetopt no_match

# swap craptastic oh-my-zsh defaults, if I want to do search I use C-r
[[ -n "${key[Up]}" ]] && bindkey "${key[Up]}" up-line-or-history
[[ -n "${key[Down]}" ]] && bindkey "${key[Down]}" down-line-or-history
# PgUP/PgDn
[[ -n "${terminfo[kpp]}" ]] &&  bindkey "${terminfo[kpp]}" up-line-or-search
[[ -n "${terminfo[knp]}" ]] &&  bindkey "${terminfo[knp]}" down-line-or-search
