#!/bin/sh
# <%= @puppet_header %>
# <%=  __FILE__.gsub(/.*?repos/,@fqdn + ':') %>
if [ -e /var/run/vpnc.pid ] ; then
   /usr/share/i3blocks/network
elif [ -e /usr/sbin/vpnc ] ; then
    echo "↓"
    echo "↓"
    echo "#FF0000"
else
    echo ""
    echo ""
    echo "#FF0000"
fi
