#!/usr/bin/perl
open(DEVLIST,'-|','xinput');
while(<DEVLIST>) {
    if ($_ =~ /id=(\d+)/) {
        my $dev_id=$1;
        if ($_ =~ /pointer/ && $_ !~ /keyboard/i && $dev_id > 4) {
            system('xinput', 'set-prop', $dev_id, 'Device Accel Profile', '-1');
            # also called "libinput Accel Speed" or "shit actually worked so we had to refactor it to break it again"
            system('xinput', 'set-prop', $dev_id, '274', '-1');
        }
    }
}
system("xinput set-prop 9 'Device Accel Profile' -1");
system("xinput set-prop 10 'Device Accel Profile' -1");
