#!/usr/bin/perl
# Puppet: <%=  __FILE__.gsub(/.*?repos/,@fqdn + ':') %>
use common::sense;
my ($title, $body) = @ARGV;
my $icon ||= 'preferences-system-network';
$body =~ s/\&/\&amp\;/g;
$body =~ s/</\&lt\;/g;
$body =~ s/>/\&gt\;/g;
$body =~ s{http(|s)://(.+)(\s|$)}{<a href="http\1://\2">\2</a>\3}g;
print "$title $body \n";
system('notify-send',"--icon=$icon",$title,$body);
