#!/bin/bash
# <%= @puppet_header %>
# <%=  __FILE__.gsub(/.*?repos/,@fqdn + ':') %>
source /home/xani/env.xsession
sudo -u xani /usr/local/bin/notify-wrapper puppet "$1" /usr/share/icons/oxygen/128x128/categories/applications-utilities.png
