#!/bin/bash
# <%= @puppet_header %>
# <%=  __FILE__.gsub(/.*?repos/,@fqdn + ':') %>

# run tests, output only if changed

GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT"

if [ ! -e tmp ] ; then
   mkdir tmp
fi

TESTCMD="./test.sh"
TESTCMD_PREFIX=""

if [ ! -e "$TESTCMD" ]; then
   if [ -e cpanfile ] ; then
       carton install
       TESTCMD_PREFIX = "carton exec"
   fi
   if [ -e Makefile.PL ]; then
       if [ ! -e Makefile ] ; then
           $TESTCMD_PREFIX perl Makefile.PL
           TESTCMD="make test"
       fi
   fi
fi
echo "running tests"
rm tmp/test-new tmp/test-old || true
touch tmp/test-new tmp/test-old
spinner='/-\|'
while sleep 1 ; do
    $TESTCMD_PREFIX $TESTCMD 2>&1 | grep -v -P 'wallclock secs' > tmp/test-new
    if diff  tmp/test-new tmp/test-old >/dev/null 2>&1 ;then
        if [ "z$NOSPIN" = "z" ] ; then
           printf '\b%.1s' "$spinner"
        fi
        spinner=${spinner#?}${spinner%???}
    else
        clear
        cat tmp/test-new
        cp tmp/test-new tmp/test-old
    fi
done
