#!/bin/bash
# Puppet: <%=  __FILE__.gsub(/.*?repos/,@fqdn + ':') %>
file=$(find /tmp -maxdepth 1 -type f |grep -P '^/tmp/(dump.*|.*pcap)$' |sort|rofi -dmenu)

if pkill -f -9 "wireshark $file" ;then
    sleep 0.5
    for a in 0.5 1 1 2 2 ; do
       if pkill -f -9 "wireshark $file" ;then
          sleep $a
       else
           break
       fi
    done
fi
wireshark "$file" &
