#!/bin/bash
# puppet managed template, for more info 'puppet-find-resources $filename'
# <%=  __FILE__.gsub(/.*?modules\//,'puppet://modules/') %>

DAY=`date +%u`

if [ $DAY = "6" ] ; then exit 0; fi
if [ $DAY = "7" ] ; then exit 0; fi

exec "$@"
