class home::vars (
    $homedir              = lookup('homedir',undef,undef,'/home/xani'),
    $http_proxy           = lookup('http_proxy',undef,undef,false),
    $https_proxy          = lookup('https_proxy',undef,undef,false),
    $socks_proxy          = lookup('socks_proxy',undef,undef,false),
    $no_proxy             = lookup('no_proxy',undef,undef,false),
    $perl5lib             = lookup('perl5lib',undef,undef,false),
    $git                  = lookup('git'),
    $git_work             = lookup('git_work'),
    $xrandr_left          = lookup('xrandr_left',undef,undef,"DisplayPort-2"),
    $xrandr_right         = lookup('xrandr_right',undef,undef,"HDMI-A-0"),
    $i3_composite         = lookup('i3_composite',undef,undef,true),
    $i3_composite_backend = lookup('i3_composite_backend',undef,undef,false),
    $gpgid                = lookup('gpgid',undef,undef,false),
    $conky_xinerama_head  = lookup('conky_xinerama_head',undef,undef,false),
    $goprivate            = lookup('goprivate',undef,undef,false),
) {}
