HTTP/1.0 200 OK
Cache-Control: no-cache
Connection: close
Content-Type: text/html
Retry-After: 20

<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

