;;; xani-jabber.el ---
;;
(custom-set-variables
 '(jabber-default-priority 100)
 '(jabber-default-status "RIP {+} Google Reader. We will miss you" )
 '(jabber-activity-make-strings (quote jabber-activity-make-strings-shorten))
 '(jabber-activity-shorten-minimum 20)
 '(jabber-alert-message-hooks (quote (jabber-message-beep jabber-message-echo jabber-message-scroll)))
 '(jabber-alert-presence-hooks nil)
 '(jabber-auto-reconnect t)
 '(jabber-autoaway-method (quote jabber-xprintidle-get-idle-time))
 '(jabber-autoaway-status "AFK")
 '(jabber-autoaway-priority -10)
 '(jabber-autoaway-timeout 15)
 '(jabber-backlog-days 90.0)
 '(jabber-backlog-number 1000)
 '(jabber-default-priority 10)
 '(jabber-history-enable-rotation t)
 '(jabber-history-enabled t)
 '(jabber-history-size-limit 65535)
 '(jabber-mode-line-mode t)
 '(jabber-muc-default-nicknames nil)
 '(jabber-post-connect-hooks (quote (jabber-send-current-presence jabber-muc-autojoin jabber-keepalive-start jabber-vcard-avatars-find-current jabber-autoaway-start jabber-mode-line-mode)))
 '(jabber-reconnect-delay 60)
 '(jabber-roster-show-empty-group t)
 '(jabber-roster-line-format "%c %-25n %u %-8s  %S")
 '(jabber-use-global-history nil)
 '(jabber-chat-buffer-show-avatar nil)
 '(jabber-history-dir "~/emacs/jabber-history")
 )
(custom-set-faces
       '(jabber-activity-face ((t (:foreground "#ffaa00" :weight bold))))
       '(jabber-activity-personal-face ((t (:foreground "#aaaaff" :weight bold))))
       '(jabber-chat-prompt-foreign ((t (:foreground "#66cc55" :weight bold))))
       '(jabber-chat-prompt-local ((t (:foreground "#aaaacc" :weight bold))))
       '(jabber-chat-text-local ((t (:foreground "#aaaaff"))))
       '(jabber-roster-user-online ((t (:foreground "#5577aa" :slant normal :weight bold))))
)

(require 'xani-notify)
(add-hook 'jabber-alert-message-hooks 'libnotify-jabber-notify)

(provide 'xani-jabber)